$RTL_ROOT/third_party/pccx-v002/LLM/rtl/packages/isa/isa_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/perf_counter_pkg.sv
$RTL_MEM/Constant_Memory/shape_const_ram.sv
$RTL_MEM/mem_BUFFER.sv
$RTL_MEM/mem_L2_cache_fmap.sv
$RTL_MEM/mem_GLOBAL_cache.sv
$RTL_MEM/mem_u_operation_queue.sv
$RTL_MEM/mem_CVO_stream_bridge.sv
$RTL_MEM/mem_dispatcher.sv
