${RTL_DTYPE_PKG}
${RTL_MAT}/GEMM_dsp_packer.sv
${RTL_MAT}/GEMM_sign_recovery.sv
${RTL_MAT}/GEMM_dual_mac_recover.sv
${RTL_MAT}/GEMM_accumulator.sv
${RTL_MAT}/GEMM_dsp_unit.sv
${RTL_MAT}/GEMM_dsp_unit_last_ROW.sv
${RTL_MAT}/GEMM_fmap_staggered_delay.sv
${RTL_MAT}/GEMM_weight_dispatcher.sv
${RTL_MAT}/GEMM_systolic_array.sv
${RTL_MAT}/GEMM_systolic_top.sv
${RTL_MAT}/mat_result_normalizer.sv
${RTL_MAT}/FROM_mat_result_packer.sv
