$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/dtype_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/device_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/mem_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/perf_counter_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/vec_core_pkg.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/BF16_math.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/packages/Algorithms.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/interfaces/IF_queue.sv
$RTL_ROOT/third_party/pccx-v002/common/rtl/wrappers/QUEUE.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/packages/isa/isa_pkg.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/ctrl_npu_decoder.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/AXIL_CMD_IN.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/AXIL_STAT_OUT.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/ctrl_npu_frontend.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/npu_controller_top.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/controller/Global_Scheduler.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/Constant_Memory/shape_const_ram.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_BUFFER.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_L2_cache_fmap.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_GLOBAL_cache.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_u_operation_queue.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_CVO_stream_bridge.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_dispatcher.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/memory/mem_HP_buffer.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/preprocess/preprocess_bf16_fixed_pipeline.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/preprocess/fmap_cache.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/preprocess/preprocess_fmap.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_dsp_packer.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_sign_recovery.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_dual_mac_recover.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_accumulator.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_dsp_unit.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_dsp_unit_last_ROW.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_fmap_staggered_delay.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_inst_fmap_aligner.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_weight_dispatcher.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/mat_result_normalizer.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/FROM_mat_result_packer.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_systolic_array.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/mat/GEMM_systolic_top.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/vec/GEMV_generate_lut.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/vec/GEMV_reduction_branch.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/vec/GEMV_reduction.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/vec/GEMV_accumulate.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/vec/GEMV_top.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/cvo/CVO_sfu_unit.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/cvo/CVO_cordic_unit.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/core/cvo/CVO_top.sv
$RTL_ROOT/third_party/pccx-v002/LLM/rtl/top/pccx_npu_top.sv
$RTL_ROOT/hw/vivado/npu_core_wrapper.sv
