//`define //
`define WEIGHT_HP_PORT_SIZE 512
`define FEATURE_MAP_HPC_PORT_SIZE 256

//`define INPUT_weight
`define IS_NEGATIVE_NUMBER 1
`define WEIGHT_SIZE 4
`define FEAUTRE_MAP_SIZE 16
`define AXI_WEIGHT_PORT_CNT 4


`define GEMV_LOW 0
`define GEMV_HIGH 1


`define GEMV_MAX_RES_VEC 2048

`define GEMV_QUARTER_ONE 0
`define GEMV_QUARTER_TWO 1
`define GEMV_QUARTER_THREE 2
`define GEMV_QUARTER_FOUR 3
